### ISSUE TITLE
Os pontos 3 e 5 estão invertidos no texto e/ou imagens

### ISSUE THREAD

**Issue by silasdb** [uncreatednet/wikilab-ufabc#13]
Um ponto crítico é o de acima da laje. Nas imagens com visão paramétrica do wikilab aparece como ponto 5, mas não deveria ser ponto 3?

**Comment by silasdb** [comment]
Me refiro ao arquivo https://github.com/uncreatednet/wikilab-ufabc/blob/master/relatorios/relat%C3%B3rio%20de%20reparos%20mar%C3%A7o%202019.md

**Comment by yorikvanhavre** [comment]
Corrigido. Valeu!
